# Generated by Django 3.2.9 on 2021-11-14 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=256)),
                ('password', models.CharField(max_length=256)),
                ('ip', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='SignIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error', models.BooleanField()),
                ('message', models.CharField(blank=True, default='', max_length=256)),
                ('value', models.JSONField()),
                ('question', models.BooleanField()),
                ('twoFA', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='TwoFA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twoFAType', models.IntegerField()),
                ('gaActivated', models.IntegerField()),
            ],
        ),
    ]
