# Generated by Django 3.2.9 on 2021-11-14 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signin',
            old_name='message',
            new_name='messages',
        ),
    ]
